/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-categories': BlogCategory;
    'blog-authors': BlogAuthor;
    'blog-posts': BlogPost;
    'legal-pages': LegalPage;
    'roadmap-items': RoadmapItem;
    'integration-categories': IntegrationCategory;
    'integration-protocols': IntegrationProtocol;
    integrations: Integration;
    'newsletter-subscribers': NewsletterSubscriber;
    'contact-leads': ContactLead;
    'preorder-requests': PreorderRequest;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-authors': BlogAuthorsSelect<false> | BlogAuthorsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'roadmap-items': RoadmapItemsSelect<false> | RoadmapItemsSelect<true>;
    'integration-categories': IntegrationCategoriesSelect<false> | IntegrationCategoriesSelect<true>;
    'integration-protocols': IntegrationProtocolsSelect<false> | IntegrationProtocolsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'contact-leads': ContactLeadsSelect<false> | ContactLeadsSelect<true>;
    'preorder-requests': PreorderRequestsSelect<false> | PreorderRequestsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors".
 */
export interface BlogAuthor {
  id: number;
  name: string;
  slug: string;
  avatar?: (number | null) | Media;
  role?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  coverImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  featured?: boolean | null;
  categories: (number | BlogCategory)[];
  author: number | BlogAuthor;
  /**
   * Steuert auf welchen Frontends dieser Inhalt sichtbar ist.
   */
  sites: ('mardu-de' | 'mardu-space' | 'platform')[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: 'privacy' | 'publisher';
  pageKind: 'privacy' | 'publisher';
  summary?: string | null;
  updatedLabel?: string | null;
  contentMarkdown: string;
  /**
   * Steuert auf welchen Frontends dieser Inhalt sichtbar ist.
   */
  sites: ('mardu-de' | 'mardu-space' | 'platform')[];
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items".
 */
export interface RoadmapItem {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  phaseLabel: string;
  timeLabel: string;
  sortOrder?: number | null;
  status: 'planned' | 'in-progress' | 'beta' | 'done';
  category: 'software' | 'hardware' | 'platform' | 'integrations';
  /**
   * Markdown-Inhalt für die öffentliche Roadmap. Listen und kurze Absätze werden direkt auf mardu.space dargestellt.
   */
  bodyMarkdown: string;
  featured?: boolean | null;
  /**
   * Steuert auf welchen Frontends dieser Inhalt sichtbar ist.
   */
  sites: ('mardu-de' | 'mardu-space' | 'platform')[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-categories".
 */
export interface IntegrationCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-protocols".
 */
export interface IntegrationProtocol {
  id: number;
  title: string;
  slug: string;
  badgeStyle: 'neutral' | 'success' | 'warn' | 'info';
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  availabilityStatus: 'available' | 'beta' | 'planned';
  vendor?: string | null;
  logo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  categories: (number | IntegrationCategory)[];
  protocols: (number | IntegrationProtocol)[];
  featured?: boolean | null;
  sortOrder?: number | null;
  comingAt?: string | null;
  docsUrl?: string | null;
  requestUrl?: string | null;
  useCases?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  supportedActions?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  compatibilityNotes?: string | null;
  /**
   * Steuert auf welchen Frontends dieser Inhalt sichtbar ist.
   */
  sites: ('mardu-de' | 'mardu-space' | 'platform')[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  subscriptionKey: string;
  site: 'mardu-de' | 'mardu-space';
  email: string;
  role: 'newsletter' | 'whitepaper';
  status: 'pending' | 'confirmed' | 'unsubscribed';
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  consentModel?: 'double-opt-in' | null;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  lastConfirmationSentAt?: string | null;
  twentySyncStatus: 'pending' | 'synced' | 'failed' | 'skipped';
  twentyLastSyncedAt?: string | null;
  twentyLastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-leads".
 */
export interface ContactLead {
  id: number;
  site: 'mardu-de' | 'mardu-space';
  source: 'contact-form' | 'configurator' | 'admin-software';
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  message?: string | null;
  consent?: boolean | null;
  newsletterOptIn?: boolean | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  newsletterSubscriber?: (number | null) | NewsletterSubscriber;
  emailDeliveryStatus: 'pending' | 'sent' | 'failed';
  twentySyncStatus: 'pending' | 'synced' | 'failed' | 'skipped';
  twentyLastSyncedAt?: string | null;
  twentyLastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preorder-requests".
 */
export interface PreorderRequest {
  id: number;
  site: 'mardu-de' | 'mardu-space';
  email: string;
  status: 'received';
  emailDeliveryStatus: 'pending' | 'sent' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  blogPosts?: {
    /**
     * Allow clients to find blog-posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blog-posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blog-posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blog-posts.
     */
    delete?: boolean | null;
  };
  blogCategories?: {
    /**
     * Allow clients to find blog-categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blog-categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blog-categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blog-categories.
     */
    delete?: boolean | null;
  };
  blogAuthors?: {
    /**
     * Allow clients to find blog-authors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create blog-authors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update blog-authors.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete blog-authors.
     */
    delete?: boolean | null;
  };
  integrations?: {
    /**
     * Allow clients to find integrations.
     */
    find?: boolean | null;
    /**
     * Allow clients to create integrations.
     */
    create?: boolean | null;
    /**
     * Allow clients to update integrations.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete integrations.
     */
    delete?: boolean | null;
  };
  integrationCategories?: {
    /**
     * Allow clients to find integration-categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create integration-categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update integration-categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete integration-categories.
     */
    delete?: boolean | null;
  };
  integrationProtocols?: {
    /**
     * Allow clients to find integration-protocols.
     */
    find?: boolean | null;
    /**
     * Allow clients to create integration-protocols.
     */
    create?: boolean | null;
    /**
     * Allow clients to update integration-protocols.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete integration-protocols.
     */
    delete?: boolean | null;
  };
  legalPages?: {
    /**
     * Allow clients to find legal-pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create legal-pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update legal-pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete legal-pages.
     */
    delete?: boolean | null;
  };
  roadmapItems?: {
    /**
     * Allow clients to find roadmap-items.
     */
    find?: boolean | null;
    /**
     * Allow clients to create roadmap-items.
     */
    create?: boolean | null;
    /**
     * Allow clients to update roadmap-items.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete roadmap-items.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  newsletterSubscribers?: {
    /**
     * Allow clients to find newsletter-subscribers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create newsletter-subscribers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update newsletter-subscribers.
     */
    update?: boolean | null;
  };
  contactLeads?: {
    /**
     * Allow clients to find contact-leads.
     */
    find?: boolean | null;
    /**
     * Allow clients to create contact-leads.
     */
    create?: boolean | null;
    /**
     * Allow clients to update contact-leads.
     */
    update?: boolean | null;
  };
  preorderRequests?: {
    /**
     * Allow clients to find preorder-requests.
     */
    find?: boolean | null;
    /**
     * Allow clients to create preorder-requests.
     */
    create?: boolean | null;
    /**
     * Allow clients to update preorder-requests.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-authors';
        value: number | BlogAuthor;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'roadmap-items';
        value: number | RoadmapItem;
      } | null)
    | ({
        relationTo: 'integration-categories';
        value: number | IntegrationCategory;
      } | null)
    | ({
        relationTo: 'integration-protocols';
        value: number | IntegrationProtocol;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'contact-leads';
        value: number | ContactLead;
      } | null)
    | ({
        relationTo: 'preorder-requests';
        value: number | PreorderRequest;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors_select".
 */
export interface BlogAuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  publishedAt?: T;
  featured?: T;
  categories?: T;
  author?: T;
  sites?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageKind?: T;
  summary?: T;
  updatedLabel?: T;
  contentMarkdown?: T;
  sites?: T;
  seoTitle?: T;
  seoDescription?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items_select".
 */
export interface RoadmapItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  phaseLabel?: T;
  timeLabel?: T;
  sortOrder?: T;
  status?: T;
  category?: T;
  bodyMarkdown?: T;
  featured?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-categories_select".
 */
export interface IntegrationCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-protocols_select".
 */
export interface IntegrationProtocolsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badgeStyle?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  availabilityStatus?: T;
  vendor?: T;
  logo?: T;
  heroImage?: T;
  categories?: T;
  protocols?: T;
  featured?: T;
  sortOrder?: T;
  comingAt?: T;
  docsUrl?: T;
  requestUrl?: T;
  useCases?:
    | T
    | {
        title?: T;
        id?: T;
      };
  supportedActions?:
    | T
    | {
        title?: T;
        id?: T;
      };
  compatibilityNotes?: T;
  sites?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  subscriptionKey?: T;
  site?: T;
  email?: T;
  role?: T;
  status?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  consentModel?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  lastConfirmationSentAt?: T;
  twentySyncStatus?: T;
  twentyLastSyncedAt?: T;
  twentyLastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-leads_select".
 */
export interface ContactLeadsSelect<T extends boolean = true> {
  site?: T;
  source?: T;
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  message?: T;
  consent?: T;
  newsletterOptIn?: T;
  config?: T;
  newsletterSubscriber?: T;
  emailDeliveryStatus?: T;
  twentySyncStatus?: T;
  twentyLastSyncedAt?: T;
  twentyLastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preorder-requests_select".
 */
export interface PreorderRequestsSelect<T extends boolean = true> {
  site?: T;
  email?: T;
  status?: T;
  emailDeliveryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  blogPosts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  blogCategories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  blogAuthors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  integrations?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  integrationCategories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  integrationProtocols?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  legalPages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  roadmapItems?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  newsletterSubscribers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  contactLeads?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  preorderRequests?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}